### ISSUE TITLE
Can't run dnschef.py

### ISSUE THREAD

**Issue by kenantan32** [iphelix/dnschef#21]
root@kali:~/Desktop/dnschef-master# ./dnschef.py 
Traceback (most recent call last):
  File "./dnschef.py", line 40, in <module>
    from dnslib import *
ModuleNotFoundError: No module named 'dnslib'

**Comment by Deric-W** [comment]
Did you installed dnslib as listed in requirements.txt?

**Comment by lukeh990** [comment]
I'm getting it to i ran pip3 list and there dnslib was installed but DNSChef did not see it

**Comment by MatP-MatP** [comment]
Got the same issue, but if you install it using pip, you must run pip as root, as you must provide privilege access to run dnschef, if not, it will install it into you std user so try:
sudo pip3 install dnslib

**Comment by hotelzululima** [comment]
hmm I have tried both sudo -H  pip3 install -r requirements.txt as well.. but no joy.. 

still getting**
 Traceback (most recent call last):
  File "./dnschef.py", line 40, in <module>
    from dnslib import *
ModuleNotFoundError: No module named 'dnslib'
➜  dnschef git:(master) 


os is OSX catalina .3 python3

any ideas?

**Comment by y2k04** [comment]
@kynanelliot @RandomProrammer @hotelzululima 
`python -m pip install dnslib`

You don't need to run pip as root because it is literally just downloading and moving python files which represents dnslib.
